### ISSUE TITLE
failed to add custom block

### ISSUE THREAD

**Issue by Manivannan-maker** [edgeimpulse/edge-detection-processing-block#1]
![image](https://user-images.githubusercontent.com/70482136/137261365-a649969d-932f-4bf9-a3af-9b873dce63ae.png)

I am facing above issue while following the steps. 

But in browser , this block can be accessible
![image](https://user-images.githubusercontent.com/70482136/137261569-a6661c9c-5b78-4e66-88dd-dd2cae5c902f.png)

**Comment by ferjm** [comment]
@Manivannan-maker did you manage to make it work? Looking at the error message, this looks like a temporary server issue. I've just checked that it is possible to add custom blocks, so I am closing this issue. Feel free to reopen it if you think this is still valid.
